### ISSUE TITLE
Cannot copy the required library into /usr/lib --- not permitted

### ISSUE THREAD

**Issue by enzyme69** [marek-simonik/record3d_unity_demo#1]
I am following your tutorial but stuck here:
192-168-1-7:lib jimmygunawan$ sudo cp /Users/jimmygunawan/Downloads/librecord3d_unity_streaming.dylib .

Operation not permitted. And I cannot just drag and drop in Finder either.

**Comment by marek-simonik** [comment]
@enzyme69 
If you are unable to copy even with `sudo`, then is an alternative you can try; make a new folder in e.g. Documents — let's call it `record3d_lib` — into which you copy `librecord3d_unity_streaming.dylib` and then you just add `record3d_lib` into the `DYLD_LIBRARY_PATH`:

```
# Copy the .dylib into a folder
mkdir /Users/jimmygunawan/Downloads/record3d_lib
cd /Users/jimmygunawan/Downloads/record3d_lib
cp /Users/jimmygunawan/Downloads/librecord3d_unity_streaming.dylib ./

# Open .bash_profile to save the "library-lookup" folder
open /Users/jimmygunawan/.bash_profile
```
Add this line on the end of `.bash_profile` and save it:
```
export DYLD_LIBRARY_PATH="/Users/jimmygunawan/Downloads/record3d_lib:$DYLD_LIBRARY_PATH"
```

Now you should be able to run the demo — let me know if that helped.

**Comment by enzyme69** [comment]
I followed your direction on file copy and path inside .bash_profile but not 100% sure if all I did was correct because I am still seeing nothing in Unity.

**Comment by enzyme69** [comment]
<img width="1018" alt="Screen Shot 2019-09-21 at 10 14 25 pm" src="https://user-images.githubusercontent.com/3952687/65373168-43723a80-dcbd-11e9-961b-0fa4b6e626c3.png">

**Comment by marek-simonik** [comment]
I updated the README with new instructions (the old instructions were meant for Mac OS 10.13).

In short: instead of copying the `.dylib` into `/usr/lib`, it should be copied into `/usr/local/lib` as that is the same place where the library gets copied when building [it](https://github.com/marek-simonik/record3d_unity_streaming) from sources.
