### ISSUE TITLE
Unity project. Any way to avoid copying dlls into Windows directory?

### ISSUE THREAD

**Issue by andybak** [marek-simonik/record3d_unity_demo#6]
It makes packaging up stuff for other users much more of a pain (need them to do it manually or use a proper installer to do it for them).

Would the dll be found if it's in the application folder? (just realised I could do a build and simply try it myself but I've typed this now and it might be useful for others wondering the same thing)

**Comment by marek-simonik** [comment]
On Windows, copying the DLL should not be necessary. In the latest version of this repo, I copied the DLL into `Assets > Scripts > record3d_unity_streaming.dll` deliberately for this purpose. Having the DLL next to the script that references it should be enough (I have tried on Windows 10).
