### ISSUE TITLE
Import video instead of stream

### ISSUE THREAD

**Issue by smallvalthoss** [marek-simonik/record3d_unity_demo#7]
I was wondering if there's a built in/easy way to take a video and, using record3d_unity_demo, play the video in Unity?

**Comment by marek-simonik** [comment]
Do you mean if there is a way to play an already recorded 3D Video in Unity instead of live-streaming via USB?

If that is your question, then yes, you can use my other demo, which does just that: https://github.com/marek-simonik/record3d_offline_unity_demo

**Comment by smallvalthoss** [comment]
> If that is your question, then yes, you can use my other demo

Thank you so much! Sorry for the dumb question :).
